### ISSUE TITLE
Dubious performance of FlatList with only 500 items and 1 <Text> element in each

### ISSUE THREAD

**Issue by alexweej** [microsoft/react-native-macos#1119]
### Environment

```markdown
react-native -v:
% react-native -v 
zsh: command not found: react-native
% npx react-native -v
error: unknown option `-v'


npm ls react-native-macos:
% npm ls react-native-macos
superpower@0.0.1 /Users/alex/dev/superpower
└── react-native-macos@0.64.28

node -v:
% node -v
v16.14.0

npm -v:
% npm -v
8.3.1

yarn --version:
% yarn --version
zsh: command not found: yarn

xcodebuild -version:
% xcodebuild -version 
Xcode 13.2.1
Build version 13C100
```

### Steps to reproduce the bug

```
const data = Array.from({length: 500}, (_, i) => ({
  id: i,
  text: `This is another item with index ${i}`,
}));

function App() {
  return (
    <FlatList
      ItemSeparatorComponent={() => <View style={{height: 2}}></View>}
      data={data}
      renderItem={({item}) => <Text>{item.text}</Text>}
    />
  );
}
```

Running this with `npm run macos` and scrolling through the list frequently stutters and shows blank temporarily while views are rendered. This is on a 2018 MacBook Pro. In my real application the item views are a fair bit more complex so this test case demonstrates the problem to a lesser extent than I am experiencing.

### Expected Behavior

Smoother scrolling

### Actual Behavior

Stuttered rendering while scrolling.

### Reproducible Demo

I can provide this if need be, possibly I'm just doing something obviously wrong.

### Additional context

I'm not aware of any way to run a react-native-macos app in production mode. AFAIUI React does a lot of sanity checking when running in dev mode, and maybe this is part of the problem...

Thanks!

**Comment by ospfranco** [comment]
I'm seeing the same problem in my app, in my case I have a row of emojis displayed in a flatlist, but scrolling is not smooth at all

![Screenshot 000402 2](https://user-images.githubusercontent.com/1634213/167255382-41615451-b0eb-4a86-8325-4014012286d8.gif)

**Comment by ospfranco** [comment]
Here is a simple test:

https://github.com/ospfranco/macosFlatlistTest

![Screen Recording 2022-05-12 at 18 54 38](https://user-images.githubusercontent.com/1634213/168128556-a1280f6f-86ee-4017-b0dc-1363962df4aa.gif)

- I could not reproduce the height issue, it seems only to be happening in my app
- The initial num to render is not correctly calculated/respected though, you can see even if I set a low number the rendering still goes all the way to the first 100 something, for complex views, this might be a problem (I think this is my case, I only have 50 rows, rendering all of them at once is too slow)
- Loading of more items when reaching the bottom is way too slow

**Comment by ospfranco** [comment]
Some more findings: 

- Adding a `windowSize` property helps a lot with the performance in my case, by setting it to 8 (default is 21) it only renders the visible cells
- I'm still not able to figure out why the height prop is being ignored

**Comment by Saadnajmi** [comment]
Fwiw, this should be much faster in 0.71

**Comment by ospfranco** [comment]
w00p w00p! is 0.71 out?

**Comment by Saadnajmi** [comment]
We cut the stable branch, but are having troubles publishing it to NPM 😅. Working on it...

I'm not sure what a migration guide would have that's different from a standard RN upgrade? Which to be fair.. is already not fun..

**Comment by ospfranco** [comment]
I'll give it a try! :)

**Comment by alexweej** [comment]
I just (somewhat laboriously, maybe I did it wrong :/) upgraded my react-native-macos app to 0.71.1. I ended up upgrading all dependencies (using npm-check-updates) because of a zoo of peer dependency issues. I see very little change, quite possibly *worse* performance on the FlatList browser in my app. It for some reason calls the render function on each item very slowly. I'm setting up a repro project now to check with a bit more a clean slate.

**Comment by alexweej** [comment]
OK, I can see that even setting `getItemLayout` faithfully(?) it still has bad performance. There seems to be an issue where `renderItem` is called over and over again over the range of items in the data array that have already been rendered, even from wake up where there are only 14 items visible.

I've put the whole demo project [here](https://github.com/alexweej/react-native-macos-flat-list-performance-issue/blob/main/App.tsx), and the log of a run on my system in [this gist](https://gist.github.com/alexweej/df29ed633d4fd7033f47aa1ba01d4937).

The pattern in the gist is quite predictable. It seems to decide it wants to increase the number of realized rows by 10 each time (even without any interaction), but then ends up calling the `renderItem` callback for each item, from the start, over and over again. I'm not sure if this is a red herring, but it seems odd that `renderItem` itself would be called repeatedly, right?

Thanks

**Comment by alexweej** [comment]
The React DevTools Profiler doesn't seem to indicate anything too excessive - renders taking , though this is my first time using it so I have little intuition. The fact that the main thread is spinning 100% for tens of seconds makes me think that there is a performance problem with the inter-thread communication or something. (The heaviest render is 50ms in this profile where the app was frozen filtering the items in the list.)

<img width="1354" alt="Screenshot 2023-04-10 at 17 21 50" src="https://user-images.githubusercontent.com/15476/230945252-95846807-3ff8-4957-a4f1-67b8bf9b5a18.png">

**Comment by Saadnajmi** [comment]
@alexweej The fast that `renderItem` is called many times implies to me the flatlist items aren't getting properly memoized, and are re-rendering on every update. I'm also curious, if you do the same profiling on iOS, do you see similar hangs on the main thread? If you're using hooks in renderItem, you might want to try the prop `listItemComponent` instead (that's unhelpfully not well documented I think.. but is renderItem but with better support for hooks I think).

**Comment by Saadnajmi** [comment]
Also, this might be helpful for RN-macOS upgrades... https://react-native-community.github.io/upgrade-helper/?from=0.68.69&to=0.71.0&package=react-native-macos 
They should be about the same as upgrading iOS to RN 0.71, which itself can be painful. There isn't much we can do about that unfortunately.

**Comment by alexweej** [comment]
Sorry for the silence. Life got in the way. I'm still on react-native-macos 0.71.1 but I wanted to try and debug things a bit more before attempting an upgrade. I noticed that in Xcode there is a UI tree that clearly includes fully realized views and subviews for every single item in the FlatList.

```
(lldb) po [[((RCTScrollContentView*)0x7fb7de025000) subviews] count]
409
```

Not sure if I misunderstand something about how views are retained, but this should never be the case, right?

**Comment by alexweej** [comment]
OK, I logged out the item index being passed to `renderItem` and loaded this into Google Sheets to see what was going on. It seems like some algorithm is going a bit wrong...

<img width="733" alt="Screenshot 2023-12-22 at 13 56 24" src="https://github.com/microsoft/react-native-macos/assets/15476/76b5c8da-bef0-4d2d-9786-c19f663b9237">

**Comment by alexweej** [comment]
I can confirm that I see the exact same behaviour on iOS with upstream react-native 0.71.0. From a wakeup iPhone SE screen with the following code it just calls `renderItem` in the above pattern, starting from item 0 every time and eventually reaching index 366. When I scroll down a small amount less than the row height, it clearly knows it needs to render one more row, but it starts at 0 again.

```typescript
const data = Array.from({length: 500}, (_, i) => ({
  id: i,
  text: `This is another item with index ${i}`,
}));

const ITEM_HEIGHT = 20;

function App() {
  return (
    <FlatList
      ItemSeparatorComponent={() => <View style={{height: 2}}></View>}
      data={data}
      getItemLayout={(data, index) => ({
        length: ITEM_HEIGHT,
        offset: ITEM_HEIGHT * index,
        index,
      })}
      renderItem={({ item, index }) => {
        console.log('rendering item', index);
        return <Text style={{height: ITEM_HEIGHT}}>hi {item.text}</Text>
      }}
    />
  );
}

export default App;
```

Curiously in the log I see:

>  LOG  rendering item 393
>  LOG  rendering item 394
>  LOG  VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. {"contentLength": 7372.5, "dt": 654, "prevDt": 608}
>  LOG  rendering item 0
>  LOG  rendering item 1

Given that the returned element is a `Text` element, I don't see how there's anything I can do better or more optimally. Can anyone please confirm that this seems wrong to them?

Thanks

**Comment by alexweej** [comment]
OK so it took me this long to discover that

* `windowSize` is measured in 'number of screens'
* `windowSize` default is 21

So that explains why it's trying to render so many rows... Doesn't explain why it's calling `renderItem` on rows that are already rendered to Views, though.

**Comment by bear-ei** [comment]
> @alexweej The fact that `renderItem` is called many times implies to me the flatlist items aren't getting properly memoized, and are re-rendering on every update. I'm also curious, if you do the same profiling on iOS, do you see similar hangs on the main thread? If you're using hooks in renderItem, you might want to try the prop `listItemComponent` instead (that's unhelpfully not well documented I think.. but is renderItem but with better support for hooks I think).

Can we reopen an investigation into this issue? My component has been minimized to only ```<Text>{itemKey}</Text>```, yet the scrolling performance on MacOS remains extremely poor. The complete component scrolls smoothly on iOS. I've implemented all optimizations outlined in the official React Native documentation, yet the performance remains terribly subpar, leading me to believe the issue lies at the native level.


```
 <AnimatedContainer testID={`listItem--${id}`}> // use React.memo()
            <Text>{itemKey}</Text> 
 </AnimatedContainer>
```

**Comment by Saadnajmi** [comment]
Hi, I want to say I'm aware this is still an issue, seems to be something specific to macOS (like, at the Appkit vs UIKit level) given that the same code on iOS seems to work fine, and I don't really have any leads on what's causing the issue.
