### ISSUE TITLE
Wrong image pixel density version on initial launch

### ISSUE THREAD

**Issue by AdrianFahrbach** [microsoft/react-native-macos#2084]
### Environment

```markdown
react-native -v: v0.72.10
npm ls react-native-macos: v0.72.18
node -v: v18.17.1
npm -v: v9.6.7
yarn --version: not in use
xcodebuild -version: Xcode 15.2 Build version 15C500b
```

### Steps to reproduce the bug

It seems like my React Native app is using the wrong image on initial launch. It doesn't load the @2x version but instead shows the lower res image.
I also had this issue during development, but thought it would fix itself in a production build. I'm not quite sure how (or even if) I can reproduce this during development, I definitely could reproduce it on my TestFlight build though.

1. Publish your app through TestFlight (should have an image with 1x and 2x versions)
2. Download and install the TestFlight app
3. Check the image. It seems to be loading the lower resolution version
4. Completely close/quite the app and restart it
5. The image is now loaded correctly

### Expected Behavior

It should be using the correct @2x image.

### Actual Behavior

Take a close look at the icons, especially the calendar icon on the top right:

![screenshot 2024-02-26 at 15 52 04@2x](https://github.com/microsoft/react-native-macos/assets/45072099/9d04081b-1c29-4d33-9869-d7574ca85281)

**Comment by Saadnajmi** [comment]
Any idea if this repress in 0.73 as well?

**Comment by AdrianFahrbach** [comment]
> Any idea if this repros in 0.73 as well?

I'm not quite sure, but it could very well be that this issue only occurred after downgrading to 0.72.
I will check this in the following days and then post here again.

**Comment by AdrianFahrbach** [comment]
> Any idea if this repros in 0.73 as well?

Yes, this happens on 0.73 as well. It also seems like the animations are not working.

**Comment by Saadnajmi** [comment]
Are your animations transform based? That should be fixed on 0.73 now. For the pixel density issue, I don't have an update yet unfortunately :/

**Comment by AdrianFahrbach** [comment]
> Are your animations transform based? That should be fixed on 0.73 now. For the pixel density issue, I don't have an update yet unfortunately :/

I will probably give it a try next week and keep you updated here.
Thanks you very very much for your work already though!

**Comment by AdrianFahrbach** [comment]
The transform fix didn't fix this issue.
I also still didn't find a way to reliably reproduce this.

**Comment by Saadnajmi** [comment]
Hey, so I recently have redone some refactoring of some image creation logic, which theoretically may better handle scaling (#2209 and #2219). These will land with React Native macOS 0.76. I'm not sure if there's a way to locally test this change, but wanted to give a heads up. Also for the sake of the bug, how are you loading your images? Through the `<Image>` component?

**Comment by AdrianFahrbach** [comment]
> Also for the sake of the bug, how are you loading your images? Through the <Image> component?

Yes, through the regular Image component.

**Comment by AdrianFahrbach** [comment]
@Saadnajmi Is this included in the [0.76.2](https://www.npmjs.com/package/react-native-macos/v/0.76.2) npm version of the package?
I'm not quite sure because there wasn't a GitHub release 😅

**Comment by Saadnajmi** [comment]
Re: No Github release. We're working on switching our release workflow to use `nx-release` so that we get Github releases automatically: https://github.com/microsoft/react-native-macos/pull/2266

**Comment by AdrianFahrbach** [comment]
This doesn't seem to be fixed (at least in dev mode). Logging `PixelRatio.get()` also gives me `1` instead of `2`, when the pixel ratio is off. I did find a way to reproduce this in dev mode though!

I thought that this only occurs on the first start of the application, but that seems to be wrong. I tried clearing all caches by running [this script](https://github.com/nice-af/chronos-app/blob/main/scripts/clear-cache.sh) in our project, but wasn't able to reproduce it that way.

I was able to reproduce it by doing changes to the node_modules folder. I was manually applying the patch in #2301 and after my changes to the respective file in the node_modules folder and a hot module reload, my pixel ratio was at `1` again. A full reload of the application does fix this though.

Another interesting find is that logging the pixel ratio through the native module below always returned the correct value:

```swift
import Foundation
import AppKit

@objc(PixelRatioModule)
class PixelRatioModule: NSObject {

  @objc
  func getPixelRatio(_ resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
    if let screen = NSScreen.main {
      let pixelRatio = screen.backingScaleFactor
      resolve(pixelRatio)
    } else {
      let error = NSError(domain: "", code: 200, userInfo: nil)
      reject("no_screen", "No screen found", error)
    }
  }
}
```

I'm not quite sure if that applies to the production version as well, since all of my test were done in dev mode, but it at least seems to be connected in some way.

**Comment by Saadnajmi** [comment]
Thanks. We can't rely on the main screen only as there can be multiple monitors connected. I think we rely on the key window (the window with focus) but I'm not sure. I appreciate the info, sorry this bug is still here

**Comment by AdrianFahrbach** [comment]
No worries! I did a bit more digging and found that the issue comes down to [line 34](https://github.com/microsoft/react-native-macos/blob/5bf84b103d16fac1054de68a9f88c05d062ffa45/packages/react-native/React/UIUtils/RCTUIUtils.m#L34) in `RCTUIUtils.m`:

```
  NSWindow *window = RCTKeyWindow();
  NSSize windowSize = window ? [window frame].size : CGSizeZero;
  screenSize = window ? [[window screen] frame].size : screenSize;
  CGFloat scale = window ? [[window screen] backingScaleFactor] : 1.0; // Default scale to 1.0 if window is nil
```

`RCTKeyWindow()` returns `NSApp keyWindow` [here](https://github.com/microsoft/react-native-macos/blob/5bf84b103d16fac1054de68a9f88c05d062ffa45/packages/react-native/React/Base/RCTUtils.m#L638) which is nil. I tried using `NSApp mainWindow`, but that one is nil as well. The `NSApp windows` array has my window in it though.

I guess this kind of makes sense. [Apples documentation](https://developer.apple.com/documentation/appkit/nsapplication/keywindow) says:

> The value in this property is nil when the app’s storyboard or nib file has not yet finished loading. **It might also be nil when the app is inactive or hidden.**

When I adjust the node_modules, my app is inactive and therefore doesn't have a `keyWindow`. This is could also the case when starting it for the first time, since there are probably a few other things running for the initial setup (or maybe because it was opened through the test flight app).

I guess that this isn't easy to fix, since RN is probably setup to only work with one screen?

My quick solution is to just set the default to `2.0`. Loading larger images when my app is used on an external monitor doesn't really hurt and additionally this only applies to the first launch of the app.

**Comment by AdrianFahrbach** [comment]
So it is the same issue as #2296

**Comment by Saadnajmi** [comment]
Good to know the 2x assets aren't a downgrade on a 1x screen and the two issues are related. I think we should update the logic for when the key window is nil as both this bug and the other describe, given it's in Apple documentation. I'll need to think about how to properly do the fallback.

**Comment by AdrianFahrbach** [comment]
> Yes, this happens on 0.73 as well. It also seems like the animations are not working.

I also just noticed that this is why my transform animations aren't working. The animations that aren't working are based on the window width from `useWindowDimensions`. It seems like that width is invalid as well.
"Regular" animations are working fine.
